---
- name: Install Java 1.7 and some basic dependencies
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   - libselinux-python
   - libsemanage-python
   - iptables-services

- name: Download JBoss from jboss.org
  get_url: 
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip 
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  unarchive: 
    dest: /usr/share 
    src: /opt/jboss-as-7.1.1.Final.zip 
    creates: /usr/share/jboss-as 
    copy: no 

# Rename the dir to avoid encoding the version in the init script
- name: Rename install directory
  command: chdir=/usr/share /bin/mv jboss-as-7.1.1.Final jboss-as creates=/usr/share/jboss-as

- name: Copying standalone.xml configuration file
  template: 
    src: standalone.xml 
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Download and use jboss-module-1.1.5.GA instead
  get_url:
    url: http://repo1.maven.org/maven2/org/jboss/modules/jboss-modules/1.1.5.GA/jboss-modules-1.1.5.GA.jar
    dest: /usr/share/jboss-as/jboss-modules.jar

- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  file: 
    path: /usr/share/jboss-as/ 
    owner: jboss 
    group: jboss 
    state: directory 
    recurse: yes

- name: Copy the init script
  copy: 
    src: jboss-as-standalone.sh 
    dest: /etc/init.d/jboss 
    mode: 0755

- name: Workaround for systemd bug
  shell: service jboss start && chkconfig jboss on
  ignore_errors: yes

- name: Enable JBoss to be started at boot
  service: 
    name: jboss 
    enabled: yes 
    state: started

- name: Deploy iptables rules
  template: 
    src: iptables-save 
    dest: /etc/sysconfig/iptables
  notify: restart iptables

- name: Ensure that firewalld is installed
  yum: 
    name: firewalld 
    state: present

- name: Ensure that firewalld is started
  service: 
    name: firewalld 
    state: started

- name: Deploy firewalld rules
  firewalld: 
    immediate: yes 
    port: "{{ item }}" 
    state: enabled 
    permanent: yes
  with_items:
  - "{{ http_port }}/tcp"
  - "{{ https_port }}/tcp"

- name: Update iptables
  iptables:
    chain: IN_public_allow
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
    rule_num: 1
  loop:
    - 8080
    - 8443

- name: Sending notification email
  mail:
    host: localhost
    port: 25
    to: Anthony Lin <anthony.lin.test@gmail.com>
    subject: Ansible Report
    body: "JBoss Application Server Set Up Successfully"
  delegate_to: localhost
